### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/tablefill#2]
I'm not sure if it was designed to support both Python 2 and 3, but I get errors when trying to run it with Python 3. 

Running `python fill_tables.py`, where `fill_tables.py` contains:
```py
#! /usr/bin/env python2

import glob
import os
from tablefill import tablefill

filled_names = glob.glob('filled/*.tex')
for i in filled_names:
    os.remove(i)

# Fill all latex tables in template/ except master.tex
names = [os.path.basename(x) for x in glob.glob('template/*.tex')]
for name in names:
    try:
        tablefill(template   = os.path.join("template", name),
                  output     = os.path.join("filled", name),
                  fillc      = True,
                  input      = "out/tables/tables.txt",
                  xml_tables = "parsing.xml")
    except:
        raise

```

```
Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()

Parsing arguments...
ERROR!
Traceback (most recent call last):
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 321, in tablefill
    fill_engine.get_parsed_arguments(kwargs)
  File "/home/kyle/research/doyle/eosloan/geisinger/local/miniconda/lib/python3.6/site-packages/tablefill/tablefill.py", line 673, in get_parsed_arguments
    isare = " is " if len(missing_args) == 1 else " are "
TypeError: object of type 'filter' has no len()
```

**Comment by mcaceresb** [comment]
It was designed to support python 2.6, initially. I think I just need to enclose the filter statements in `list()` for this error.

**Comment by kylebarron** [comment]
I tried yesterday to just change the `filter` statements to list comprehensions, but I believe I introduced another error.
